name: weather
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: 0.11.3+16
  path_provider: ^0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - graphics/img1.jpg
    - graphics/img2.jpg
    - graphics/img3.jpg
    - graphics/img4.jpg
    - graphics/cond_icon_heweather/100.png
    - graphics/cond_icon_heweather/101.png
    - graphics/cond_icon_heweather/102.png
    - graphics/cond_icon_heweather/103.png
    - graphics/cond_icon_heweather/104.png
    - graphics/cond_icon_heweather/200.png
    - graphics/cond_icon_heweather/201.png
    - graphics/cond_icon_heweather/202.png
    - graphics/cond_icon_heweather/203.png
    - graphics/cond_icon_heweather/204.png
    - graphics/cond_icon_heweather/205.png
    - graphics/cond_icon_heweather/206.png
    - graphics/cond_icon_heweather/207.png
    - graphics/cond_icon_heweather/208.png
    - graphics/cond_icon_heweather/209.png
    - graphics/cond_icon_heweather/210.png
    - graphics/cond_icon_heweather/211.png
    - graphics/cond_icon_heweather/212.png
    - graphics/cond_icon_heweather/213.png
    - graphics/cond_icon_heweather/300.png
    - graphics/cond_icon_heweather/301.png
    - graphics/cond_icon_heweather/302.png
    - graphics/cond_icon_heweather/303.png
    - graphics/cond_icon_heweather/304.png
    - graphics/cond_icon_heweather/305.png
    - graphics/cond_icon_heweather/306.png
    - graphics/cond_icon_heweather/307.png
    - graphics/cond_icon_heweather/309.png
    - graphics/cond_icon_heweather/310.png
    - graphics/cond_icon_heweather/311.png
    - graphics/cond_icon_heweather/312.png
    - graphics/cond_icon_heweather/313.png
    - graphics/cond_icon_heweather/400.png
    - graphics/cond_icon_heweather/401.png
    - graphics/cond_icon_heweather/402.png
    - graphics/cond_icon_heweather/403.png
    - graphics/cond_icon_heweather/404.png
    - graphics/cond_icon_heweather/405.png
    - graphics/cond_icon_heweather/406.png
    - graphics/cond_icon_heweather/407.png
    - graphics/cond_icon_heweather/500.png
    - graphics/cond_icon_heweather/501.png
    - graphics/cond_icon_heweather/502.png
    - graphics/cond_icon_heweather/503.png
    - graphics/cond_icon_heweather/504.png
    - graphics/cond_icon_heweather/507.png
    - graphics/cond_icon_heweather/508.png
    - graphics/cond_icon_heweather/900.png
    - graphics/cond_icon_heweather/901.png
    - graphics/cond_icon_heweather/999.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
